title: athisa's blog
author: athisa goh
email: tincank@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A weeb and programmer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "index" # the base hostname & protocol for your site

permalink: /:slug.html
favicon: "./logo.png?"

# Build settings
theme: no-style-please
remote_theme: riggraz/no-style-please

theme_config:
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
